import React from 'react'

const Text = () => {
    return (
        <p className='text'>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet 

        <span className="header">Conqestaur elit</span>

        Laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia.
        <br /><br/>
        Delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. 
        <br /><br/>
        Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. 

        <span className="header">Conqestaur elit</span>

        Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. 
        <br /><br/>
        Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. 
        
        <span className="header">Conqestaur elit</span>

        Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque? <br/> <br/>
        amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. </p>
    )
}

export default Text