import React from 'react'

const Text = () => {
    return (
        <p className='text'>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet 

        <span className="header">Reiciendis mollitia delectus</span>

        Laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia.
        <br /><br/>
        Integer dignissim consequat pharetra. Vivamus interdum volutpat ipsum vel blandit. Nullam eu justo luctus, iaculis eros sit amet, varius eros. Nulla sodales massa in facilisis placerat. Suspendisse venenatis tristique tellus, ut dapibus orci congue eu. Vivamus sagittis quam non justo sagittis fringilla. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis enim turpis, auctor vitae tincidunt iaculis, feugiat in justo. Curabitur elementum convallis placerat. Cras a molestie massa. Etiam commodo eros elit, eu semper ligula commodo id. Suspendisse sed leo molestie, laoreet massa id, cursus augue. Vestibulum et sapien sagittis, rhoncus nisi et, congue lectus. Nullam vulputate risus id eros tempus, et iaculis risus tristique. Nunc id leo vitae mauris dictum auctor. Sed cursus velit elit, vel pulvinar elit viverra ac. 
        <br /><br/>
        Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione commodi modi optio vitae hic assumenda amet laudantium officia animi reiciendis mollitia delectus molestias tenetur dolore fuga, culpa veritatis dicta neque?Lorem ipsum dolor sit amet consectetur, adipisicing elit. 

        <span className="header">Veritatis dicta</span>

        Sed sollicitudin felis lectus, in convallis leo dictum non. Vestibulum non consequat ex. Cras ornare, lacus efficitur euismod porttitor, justo libero congue est, laoreet placerat purus massa vitae lectus. Duis et tortor in ipsum pharetra ultrices a vel nibh. Aenean eros quam, condimentum sit amet risus ac, tincidunt faucibus ex. Pellentesque aliquet diam elit, in porta orci volutpat ut. Fusce dui sapien, congue ut vestibulum vitae, aliquam id enim. Sed commodo eget nulla et lacinia. Praesent justo nisl, tristique in egestas sed, euismod sed nibh. Sed rutrum nulla quis est accumsan bibendum. Nunc vehicula metus eu volutpat finibus. Aliquam at accumsan lectus. Fusce et mollis neque. Etiam pretium purus nec aliquet suscipit. Nam tempus tellus eu eros laoreet condimentum. Aenean vulputate sed justo vitae aliquam. 
        <br /><br/>
        Etiam malesuada sit amet nunc semper commodo. Suspendisse nec mi accumsan, eleifend ligula sit amet, efficitur nunc. Nullam sed porta nisl. Pellentesque dapibus scelerisque rhoncus. Curabitur consectetur tincidunt ornare. Aenean hendrerit elit sed odio hendrerit, in vehicula enim ornare. Cras iaculis massa vel consectetur euismod. Nulla ac congue eros. Donec volutpat odio id placerat cursus. Sed neque purus, fringilla nec sem sed, molestie iaculis ligula. Vestibulum euismod vestibulum risus, vitae ultricies dui. Morbi condimentum hendrerit sagittis. In vel tellus vel risus faucibus ultricies et vitae augue.

        Aenean quis lorem lobortis, scelerisque risus a, ornare enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis dignissim iaculis sapien vitae blandit. Quisque dui leo, elementum ac dictum quis, pulvinar id lectus. In tempor dui sem, at malesuada massa ultricies in. Suspendisse potenti. Donec sapien justo, egestas volutpat nisi at, bibendum vulputate mi. Sed purus metus, tempus eget lobortis varius, rhoncus et est. Vestibulum vitae urna non lorem vestibulum lobortis. Integer urna nibh, pulvinar non est ut, eleifend commodo dolor. Phasellus nisi magna, viverra sit amet elit at, congue tristique enim. Quisque vulputate eleifend vestibulum. Praesent pharetra fringilla urna, sed semper ligula rutrum ac. 
        
        <span className="header">Aiaculis eros sit amet</span>

        Aliquam elementum malesuada velit, non euismod purus mollis nec. Nunc elit mi, varius sed sagittis eget, facilisis pretium dui. Sed mollis aliquam leo, in feugiat massa convallis at. Duis hendrerit vitae quam sed semper. Maecenas placerat quis lacus a convallis. Sed consequat odio vel risus vestibulum cursus. Morbi at velit euismod, venenatis arcu eget, ornare mauris. Phasellus eu ornare purus. Proin ultricies justo vel dui rhoncus vulputate. Nulla lobortis ullamcorper enim, non gravida lorem imperdiet in. Maecenas enim mi, gravida pretium dignissim at, euismod ac purus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

        Nunc lacus dui, interdum nec mattis vitae, mollis ac elit. Ut feugiat arcu eu sem sodales, sit amet sagittis eros imperdiet. Maecenas pulvinar, ex id gravida pretium, diam nisi blandit lorem, et auctor nunc lectus eu nulla. Donec et ante magna. Maecenas maximus, dolor vel sollicitudin aliquet, mi orci pellentesque nunc, eget tincidunt elit sapien id tortor. Nam volutpat leo quis dui tristique luctus. Nunc gravida enim non tempus ultricies. Suspendisse nec blandit lacus. Vestibulum efficitur et nibh eu luctus. Pellentesque sodales arcu orci, ac venenatis massa rhoncus vel. Maecenas ut sollicitudin quam, ac auctor ex. Praesent ullamcorper tincidunt purus, vel pellentesque purus tempor ac.  </p>
    )
}

export default Text